# This workflow will build a Swift project
name: Release

on: 
  release:
    types: [created]

jobs:
  build-and-release:
    runs-on: macos-15
    env:
      DEVELOPER_DIR: "/Applications/Xcode_16.2.app/Contents/Developer"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Swift package
        run: swift build -c release --arch arm64 --arch x86_64  
        
      - name: Get Current Tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Run shell script with tag
        run: ./Scripts/release-artifactbundle.sh "${{ env.TAG_NAME }}"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            nest-macos.artifactbundle.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
