name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: macos-15
    env:
      DEVELOPER_DIR: "/Applications/Xcode_16.2.app/Contents/Developer"
    - uses: actions/checkout@v4
    - name: Run tests
      run: swift test
    - name: Release build
      run: swift build -c release --arch arm64 --arch x86_64  
